### ISSUE TITLE
cannot start paused container (start vs unpause)

### ISSUE THREAD

**Issue by alexisdacquay** [networkop/docker-topo#10]
Hi,
Is "unpause" something new the script must adapt to, or am I doing something wrong?

```
(testdir) arista@arista-vm-001:~/testdir$ docker-topo --create topo-extra-files/examples/v2/5-node-ls.yml 
INFO:__main__:Version 2 requires sudo. Restarting script with sudo
Traceback (most recent call last):
  File "/home/arista/testdir/bin/docker-topo", line 625, in <module>
    main()
  File "/home/arista/testdir/bin/docker-topo", line 590, in main
    started = [device.start() == 0 for (name, device) in devices.items()]
  File "/home/arista/testdir/bin/docker-topo", line 590, in <listcomp>
    started = [device.start() == 0 for (name, device) in devices.items()]
  File "/home/arista/testdir/bin/docker-topo", line 280, in start
    self._attach()
  File "/home/arista/testdir/bin/docker-topo", line 297, in _attach
    link.connect(self, interface)
  File "/home/arista/testdir/bin/docker-topo", line 489, in connect
    self.network.connect(device, interface)
  File "/home/arista/testdir/bin/docker-topo", line 421, in connect
    self._create()
  File "/home/arista/testdir/bin/docker-topo", line 412, in _create
    return self.ipdb.create(ifname=self.sideA, kind='veth', peer=self.sideB).commit()
  File "/home/arista/testdir/lib/python3.6/site-packages/pyroute2/ipdb/interfaces.py", line 583, in commit
    self.nl.link('add', **request)
  File "/home/arista/testdir/lib/python3.6/site-packages/pyroute2/iproute.py", line 1310, in link
    msg_flags=msg_flags)
  File "/home/arista/testdir/lib/python3.6/site-packages/pyroute2/netlink/nlsocket.py", line 825, in nlm_request
    return do_try()
  File "/home/arista/testdir/lib/python3.6/site-packages/pyroute2/netlink/nlsocket.py", line 804, in do_try
    callback=callback)
  File "/home/arista/testdir/lib/python3.6/site-packages/pyroute2/netlink/nlsocket.py", line 649, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (34, 'Numerical result out of range')
(testdir) arista@arista-vm-001:~/testdir$ sudo docker-topo --create topo-extra-files/examples/v2/5-node-ls.yml 
sudo: docker-topo: command not found
(testdir) arista@arista-vm-001:~/testdir$ sudo docker-topo --create topo-extra-files/examples/v2/5-node-ls.yml 
sudo: docker-topo: command not found
(testdir) arista@arista-vm-001:~/testdir$ docker-topo --create topo-extra-files/examples/v2/5-node-ls.yml 
INFO:__main__:Version 2 requires sudo. Restarting script with sudo
Traceback (most recent call last):
  File "/home/arista/testdir/lib/python3.6/site-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/home/arista/testdir/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/c2f9479a5ee20226fd24491302d0a6948c382548d6bf254352f00b6ab43fa736/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arista/testdir/bin/docker-topo", line 625, in <module>
    main()
  File "/home/arista/testdir/bin/docker-topo", line 590, in main
    started = [device.start() == 0 for (name, device) in devices.items()]
  File "/home/arista/testdir/bin/docker-topo", line 590, in <listcomp>
    started = [device.start() == 0 for (name, device) in devices.items()]
  File "/home/arista/testdir/bin/docker-topo", line 273, in start
    self.container.start()
  File "/home/arista/testdir/lib/python3.6/site-packages/docker/models/containers.py", line 374, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/arista/testdir/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/arista/testdir/lib/python3.6/site-packages/docker/api/container.py", line 1064, in start
    self._raise_for_status(res)
  File "/home/arista/testdir/lib/python3.6/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/arista/testdir/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("cannot start a paused container, try unpause instead")
(testdir) arista@arista-vm-001:~/testdir$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS                       PORTS                   NAMES
c2f9479a5ee2        ceosimage:latest    "/sbin/init"        About a minute ago   Up About a minute (Paused)   0.0.0.0:9003->443/tcp   5-node-ls_Spine-1
(testdir) arista@arista-vm-001:~/testdir$ sudo docker start c2f9479a5ee2
Error response from daemon: cannot start a paused container, try unpause instead
Error: failed to start containers: c2f9479a5ee2
(testdir) arista@arista-vm-001:~/testdir$ docker -v
Docker version 18.06.0-ce, build 0ffa825
(testdir) arista@arista-vm-001:~/testdir$ 
(testdir) arista@arista-vm-001:~/testdir$ cat topo-extra-files/examples/v2/5-node-ls.yml 
links:
  - endpoints: ["Spine-1:eth0", "Spine-2:eth0", "Leaf-1:eth0", "Leaf-2:eth0", "Leaf-3:eth0"]
    driver: bridge
  - endpoints: ["Spine-1:eth1", "Leaf-1:eth1"]
  - endpoints: ["Spine-1:eth2", "Leaf-2:eth1"]
  - endpoints: ["Spine-1:eth3", "Leaf-3:eth1"]
  - endpoints: ["Spine-2:eth1", "Leaf-1:eth2"]
  - endpoints: ["Spine-2:eth2", "Leaf-2:eth2"]
  - endpoints: ["Spine-2:eth3", "Leaf-3:eth2"]

VERSION: 2
driver: veth
PREFIX: 5-node-ls
CONF_DIR: ./config
CEOS_IMAGE: ceosimage:latest
PUBLISH_BASE: 9000
(testdir) arista@arista-vm-001:~/testdir$ sudo docker info
Containers: 1
 Running: 0
 Paused: 1
 Stopped: 0
Images: 1
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-23-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 125.9GiB
Name: arista-vm-001
ID: BCLN:AZKL:J3WW:EZZT:T5OL:7X7Q:UPJO:UYIB:XHH3:SJPV:OBDJ:JETC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
(testdir) arista@arista-vm-001:~/testdir$ 


```

**Comment by networkop** [comment]
seems like you have some stale containers. try running --delete before trying --create. or simply run docker rm -f $(docker ps -aq) to clean up all started containers

**Comment by networkop** [comment]
also try renaming 5-node-ls.yml to something shorted like 5-node.yml.

**Comment by alexisdacquay** [comment]
I did all that and it worked. Thank you.
