### ISSUE TITLE
pyroute2: no IPRoute module for the platform on macOS Mojave 10.14.3

### ISSUE THREAD

**Issue by titom73** [networkop/docker-topo#17]
When using requirements included in `setup.py` generate an error when trying to run docker-topo on a macOS platform (Mojave 10.14.3). Below are some notes:

Installation without virtualenv using `pip3`

```shell
$ pip3 install git+https://github.com/networkop/docker-topo.git --user
Collecting git+https://github.com/networkop/docker-topo.git
  Cloning https://github.com/networkop/docker-topo.git to /private/var/folders/bj/x0pdlg4s46vbk9t8916xkfb00000gn/T/pip-req-build-fidxsnb6
Requirement already satisfied (use --upgrade to upgrade): docker-topo==2.0.2 from git+https://github.com/networkop/docker-topo.git in /usr/local/lib/python3.7/site-packages
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/site-packages (from docker-topo==2.0.2) (3.13)
Requirement already satisfied: docker in /usr/local/lib/python3.7/site-packages (from docker-topo==2.0.2) (3.7.0)
Requirement already satisfied: netaddr in /usr/local/lib/python3.7/site-packages (from docker-topo==2.0.2) (0.7.19)
Requirement already satisfied: pyroute2==0.5.2 in /usr/local/lib/python3.7/site-packages (from docker-topo==2.0.2) (0.5.2)
Requirement already satisfied: docker-pycreds>=0.4.0 in /usr/local/lib/python3.7/site-packages (from docker->docker-topo==2.0.2) (0.4.0)
Requirement already satisfied: requests!=2.18.0,>=2.14.2 in /usr/local/lib/python3.7/site-packages (from docker->docker-topo==2.0.2) (2.21.0)
Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python3.7/site-packages (from docker->docker-topo==2.0.2) (0.54.0)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.7/site-packages (from docker->docker-topo==2.0.2) (1.12.0)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker->docker-topo==2.0.2) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker->docker-topo==2.0.2) (2018.11.29)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker->docker-topo==2.0.2) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker->docker-topo==2.0.2) (1.24.1)
Building wheels for collected packages: docker-topo
  Running setup.py bdist_wheel for docker-topo ... done
  Stored in directory: /private/var/folders/bj/x0pdlg4s46vbk9t8916xkfb00000gn/T/pip-ephem-wheel-cache-l39eoe83/wheels/2d/13/44/613210af05f2abcdc58fdcc3ae040cd2fe8ccb398deff1859d
Successfully built docker-topo
```

Error message is related to `pyroute2` and `IPRoute`

```shell
$ docker-topo -h
Traceback (most recent call last):
  File "/usr/local/bin/docker-topo", line 11, in <module>
    from pyroute2 import IPDB
  File "/usr/local/lib/python3.7/site-packages/pyroute2/__init__.py", line 19, in <module>
    from pyroute2.iproute import (IPRoute,
  File "/usr/local/lib/python3.7/site-packages/pyroute2/iproute/__init__.py", line 141, in <module>
    raise ImportError('no IPRoute module for the platform')
ImportError: no IPRoute module for the platform
```

Python3 modules are:

```shell
$ pip3 list
Package          Version
---------------- ----------
certifi          2018.11.29
chardet          3.0.4
docker           3.7.0
docker-pycreds   0.4.0
docker-topo      2.0.2
idna             2.8
netaddr          0.7.19
pip              18.1
pyroute2         0.5.2
PyYAML           3.13
requests         2.21.0
setuptools       40.6.3
six              1.12.0
urllib3          1.24.1
websocket-client 0.54.0
wheel            0.32.3
```

After upgrading pyroute2 from `0.5.2` to `latest` (`0.5.3`), `docker-topo` can start as expected:

```shell
$ pip3 install --upgrade pyroute2
Collecting pyroute2
  Downloading https://files.pythonhosted.org/packages/19/1c/fc2efd9dfa5c1f7f713dbfee621365ad01f7b7ec0a6908e444f08bfd5873/pyroute2-0.5.3.tar.gz (687kB)
    100% |████████████████████████████████| 696kB 2.2MB/s
Building wheels for collected packages: pyroute2
  Running setup.py bdist_wheel for pyroute2 ... done
  Stored in directory: /Users/tgrimonet/Library/Caches/pip/wheels/3a/8d/19/a02a0af7742b48122d4ee7aa1f5ae9fa4833ec6043fc74052b
Successfully built pyroute2
docker-topo 2.0.2 has requirement pyroute2==0.5.2, but you'll have pyroute2 0.5.3 which is incompatible.
Installing collected packages: pyroute2
  Found existing installation: pyroute2 0.5.2
    Uninstalling pyroute2-0.5.2:
      Successfully uninstalled pyroute2-0.5.2
Successfully installed pyroute2-0.5.3

$ docker-topo -h

usage: docker-topo [-h] [-d] [--create | --destroy] [-s] [-a] topology

Tool to create cEOS topologies

positional arguments:
  topology       Topology file

optional arguments:
  -h, --help     show this help message and exit
  -d, --debug    Enable Debug

Actions:
  Create or destroy topology

  --create       Create topology
  --destroy      Destroy topology

Save:
  Save or archive the topology

  -s, --save     Save topology configs
  -a, --archive  Archive topology file and configs
```

**Comment by networkop** [comment]
i'll do some more testing and up the version if nothing breaks.
btw, docker-topo on macos will only run in "bridge" mode, since pyroute2 is not supported on MacOS https://github.com/svinota/pyroute2/issues/437

**Comment by titom73** [comment]
Thanks for the reply.

Indeed, topology I used after the -h test was based on bridge driver.

Thanks again.

**Comment by networkop** [comment]
closed in https://github.com/networkop/docker-topo/commit/27a1b64be293cf155d3b2819e9f7ad06ee5694ab
